### ISSUE TITLE
problem about multiprocessing on jupyter notebook

### ISSUE THREAD

**Issue by sunyi1123** [attilanagy234/syntax-augmentation-nmt#62] opened 2022-05-06 11:44 UTC
Hi, I've been looking at some dependency parsing code recently and I'm getting the problem when trying to reproduce your code

code:
src/hu_nmt/data_augmentator/entrypoints/precompute_en_dependency_trees.py
`def main(data_input_path, dep_tree_output_path, file_batch_size):
    eng_dep_parser = EnglishDependencyParser()
    eng_dep_parser.file_to_serialized_dep_graph_files(data_input_path, dep_tree_output_path, int(file_batch_size))
main(data_input_path=en_path,
     dep_tree_output_path=out_path,
     file_batch_size='10000')`

problem:
TypeError: can't pickle _thread.lock objects

and log points here:
src/hu_nmt/data_augmentator/base/depedency_parser_base.py#L146
can you answer for me? looking forward to your reply~

**Comment by patrick-nanys** [comment] 2022-05-06 13:24
Hi, can you please clarify it a bit more how you tried to reproduce our code? What are the steps you took (commands you ran, etc.) to try and run our code?

**Comment by sunyi1123** [comment] 2022-05-07 05:53
> Hi, can you please clarify it a bit more how you tried to reproduce our code? What were the steps you took (commands you ran, etc.)?
I want to try to understand how subtrees are swapped, in the process I try to run the main in precompute_en_dependency_trees.py
and here is log.txt
[log.txt](https://github.com/attilanagy234/syntax-augmentation-nmt/files/8644560/log.txt)

**Comment by attilanagy234** [comment] 2022-05-07 18:37
Hi @sunyi1123 

Did you set up the repo using `Poetry` ? Just want to make sure that you're running the same package versions as we are. For example I see Python 3.7 in your log.txt, although our project is running on 3.8 (see the Poetry [toml file](https://github.com/attilanagy234/syntax-augmentation-nmt/blob/main/src/pyproject.toml#L8)). One quick workaround I can suggest is to disable multiprocessing [here](https://github.com/attilanagy234/syntax-augmentation-nmt/blob/main/src/hu_nmt/data_augmentator/dependency_parsers/english_dependency_parser.py#L17).

**Comment by sunyi1123** [comment] 2022-05-08 04:15
Thank you for your reply, I close the multi-process and it can be used normally

**Comment by patrick-nanys** [comment] 2022-05-08 12:51
Added a quick fix in bfa1ee76692b78b5b429f8d05b58839b6b58ff4e as a workaround for this problem.
I'll close the issue for now, since currently multiprocessing is not one of the main priorities of the project, but it can be reopened once this becomes a blocker for someone.

**Closed by patrick-nanys** 2022-05-08 12:51 UTC
Labels: bug
